version: '3'
services:
  project_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: supassword
    ports:
      - '3306:3306'
  builder:
    build: builder/
    env_file:
      - ./.env
    ports:
      - '8080:8080'

volumes:
  appdata: