version: '3'
services:
  project_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: supassword
    ports:
      - "3306:3306"
  builder:
    build: builder/
    ports:
      - "8080:8080"
    depends_on:
      - project_db
volumes:
  appdata: