version: '3'
services:
  project_db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env
    ports:
      - '3306:3306'
  builder:
    build: builder/
    env_file:
      - ./.env
    ports:
      - '8080:8080'

volumes:
  appdata: